[wip] Add wasm-tests branch to travis, generate blockchain tests
ewasm/tests pull request #108
Opened 2018-12-03 23:53 UTC by hugo-dc

- Added wasm-tests branch to travis config (travis still needs to be activated for this repo)
- Changed the `Network` field from `ALL` to `Byzantium`.
- Generated Blockchain tests based from GeneralStateTests

2018-12-04 00:15 UTC, axic commented
Have you seen #107 ? :)

2018-12-04 01:45 UTC, hugo-dc commented
Oh, sorry, i didn't see your PR, I think I'll only keep the Blockchain tests generation in this PR.

2018-12-04 09:54 UTC, axic commented on src/GeneralStateTestsFiller/stEWASMTests/wasmDivisionByZeroFiller.yml
> +        - "Byzantium"
Shouldn't these use single quotes just like the rest of the fields?

2018-12-04 15:47 UTC, axic commented
@hugo-dc @jwasinger can you please explain what benefit do we get with blockchain tests?

2018-12-04 16:11 UTC, hugo-dc commented
@axic I'm not sure if the schema validator checks if there is Blockchain tests for ewasm or if everything is fine after the `bcEWASM` directory got removed. I'm ok to leave blockchain tests out if not needed by the schema validation.

2018-12-04 16:51 UTC, axic commented
It only checks it because the directory exists (but is empty). @jwasinger said that for some tests blockchain tests are needed, though not sure which.

2018-12-04 22:08 UTC, axic requested changes
Please rebase over #107 once that is merged.

2019-01-17 05:21 UTC, hugo-dc commented
I think this is not needed, I initially thought it would be needed for CI but is not the case.

Please reopen if you think it makes sense to have it.

2019-01-17 05:21 UTC, closed without merging