Remove debug output from revert test
ewasm/tests pull request #20
Opened 2018-03-22 22:40 UTC by lrettig

2018-04-23 14:37 UTC, axic approved these changes

2018-04-23 14:58 UTC, lrettig commented
Don't merge yet, the test is failing, see my comment here: https://gitter.im/ewasm/Lobby?at=5adde87c109bb04332f05e91

2018-04-24 14:40 UTC, chfast requested changes
...

2018-05-02 12:25 UTC, hugo-dc commented
This test case was refilled and the expected return set back to 2 in PR https://github.com/ewasm/tests/pull/27

2018-05-02 12:25 UTC, closed without merging