Test value transfer greater than 64 bits
ewasm/tests pull request #43
Opened 2018-06-01 19:59 UTC by jakelang

@ewasm/testing I have no idea what i'm doing but this should test that `ensureCondition` in Hera works for values greater than 64 bits.

2018-06-01 20:24 UTC, jwasinger commented
Please also add a description of this test to https://notes.ethereum.org/9xX4L2QyQPmzJ0Xh3RAgJA

2018-06-01 20:35 UTC, jwasinger commented on src/GeneralStateTestsFiller/stEWASMTests/callValueExceeds64bitFiller.yml
> +call:
change the name to `callValueExceeds64bitFiller` and fill the test.  You'll get some errors ;) 

```
jwasinger@certification-hive-test03:~/projects/cpp-ethereum/build$ test/testeth -t GeneralStateTests/stEWASMTests -- --vm hera --testpath ../../tests --singletest 'callValueExceeds64bit' --filltests
Running tests using path: "../../tests"
Running 1 test case...
Test Case "stEWASMTests":
100%
/home/jwasinger/projects/cpp-ethereum/test/tools/libtesteth/TestHelper.cpp(148): error: in "GeneralStateTests/stEWASMTests": callValueExceeds64bit network not found: ALL
/home/jwasinger/projects/cpp-ethereum/test/tools/libtesteth/ImportTest.cpp(551): error: in "GeneralStateTests/stEWASMTests": callValueExceeds64bit Check State: deadbeef00000000000000000000000000000001: incorrect storage [0x38] = 0x, expected [0x38] = 0x04
Frontier data: 0 gas: 0 val: 0
/home/jwasinger/projects/cpp-ethereum/test/tools/libtesteth/TestHelper.cpp(613): error: in "GeneralStateTests/stEWASMTests": postState should not be declared in expect section!
postState:
--- 02ff5864146618008afacf94e84659304a332a719793230833d94f642565596c
     deadbeef00000000000000000000000000000000: 0 #:65535 @:56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421 $d10ca8c5a8e85b5523c36d61cb87d02bf5609d14932d2507cc3bde36d596b25e
     deadbeef00000000000000000000000000000001: 0 #:83076749736557242056487941267521535 @:56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421 $d10ca8c5a8e85b5523c36d61cb87d02bf5609d14932d2507cc3bde36d596b25e


*** 3 failures are detected (5 failures are expected) in the test module "Master Test Suite"
```

2018-06-07 21:53 UTC, hugo-dc commented
@jakelang Please add the generated json file so it can be considered by circle

2018-06-07 22:08 UTC, hugo-dc requested changes

2018-06-07 22:08 UTC, hugo-dc commented on src/GeneralStateTestsFiller/stEWASMTests/callValueExceeds64bitFiller.yml
> +            (i32.store (i32.const 56) ;; store the result so it is not returned
Here you are storing the result into the wasm memory, but you  still need to store it in the contract storage, to do that you have to use the storageStore eei method, which receives key offset, and value offset, 

for example: if you want to store in the key 0 of the storage you have to send an offset which have the value 0, in this case you could use offset 60, and I think you want to store the result which is in offset 56. so you could call storageStore method like this:

```
(call $storageStore (i32.const 60) (i32.const 56))
```

2018-06-07 22:08 UTC, hugo-dc commented on src/GeneralStateTestsFiller/stEWASMTests/callValueExceeds64bitFiller.yml
> +            56: '0x2'
If you do the changes I mention above, this will be changed to:

```
storage: {
  0: 0x2
}
```

2018-06-07 22:08 UTC, hugo-dc commented on src/GeneralStateTestsFiller/stEWASMTests/callValueExceeds64bitFiller.yml
> +            56: '0x4'
same here

2018-07-30 13:16 UTC, axic commented
@jakelang @hugo-dc @lrettig @jwasinger can this be finished?

2018-07-30 18:41 UTC, lrettig commented
Leaving for @hugo-dc and @jakelang

2018-08-01 00:04 UTC, axic commented
@lrettig is this now superseded by #51?

2018-08-01 01:15 UTC, lrettig commented
Yes I think so: https://github.com/lrettig/tests/blob/7316dd821d2302921d97e0d35293fc1fda43ba60/src/GeneralStateTestsFiller/stEWASMTests/callValueExceeds64bitFiller.yml

I'm going to close this, feel free to reopen if I've missed something.

2018-08-01 01:15 UTC, closed without merging