Basic wasm tests - part 1.
ewasm/tests pull request #86
Opened 2018-09-03 19:21 UTC by poemm

Everything is ready. I am just not sure how to compute gas balance by hand. Specifically for `wasmDivisionByZero` and `wasmUnreachable`.

2018-09-03 19:54 UTC, axic commented on src/GeneralStateTestsFiller/stEWASMTests/wasmGrowMemoryFiller.yml
> +           (get_local $keyAddress)
I think you could use `i32.const 0` here or put this comment next to `keyAddress` where it is declared, given it doesn't do an explicit `set_local`.

2018-09-03 19:54 UTC, axic commented on src/GeneralStateTestsFiller/stEWASMTests/wasmUnreachableFiller.yml
> +          ;; this division by zero should trap
I think this comment is wrong.

2018-09-03 19:56 UTC, axic commented
Looks good otherwise!

@hugo-dc do you want to check the gas calculations?

2018-09-12 01:23 UTC, hugo-dc requested changes

2018-09-12 01:23 UTC, hugo-dc commented on src/GeneralStateTestsFiller/stEWASMTests/wasmDivisionByZeroFiller.yml
> +# Test whether memory grow outputs the size that it grew
did you make any other change after filling the test case, seems this test case needs to be refilled.

2018-09-12 01:23 UTC, hugo-dc commented on src/GeneralStateTestsFiller/stEWASMTests/wasmGrowMemoryFiller.yml
> +            0: '0x0000000000000000000000000000000000000003'
For this test case I'm getting different endianess for storage 0: `0x0300000000000000000000000000000000000000000000000000000000000000`

2018-09-12 01:23 UTC, hugo-dc commented on src/GeneralStateTestsFiller/stEWASMTests/wasmUnreachableFiller.yml
> +# Test whether memory grow outputs the size that it grew
This test case needs to be refilled too.

`Test /home/ubuntu/workspace/tests/GeneralStateTests/stEWASMTests/wasmUnreachable.json in wasmUnreachable is outdated. Filler hash is different!`

2018-09-13 18:55 UTC, poemm commented
Changed endian-ness and refilled.

2018-09-17 18:30 UTC, hugo-dc approved these changes

2018-10-04 01:38 UTC, axic approved these changes

2018-10-04 01:39 UTC, merged